/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aplicacion.Categoria;
import aplicacion.Desarrolladora;
import aplicacion.FachadaAplicacion;
import java.util.ArrayList;

/**
 *
 * @author Alex
 */
public class VAnhadirJuego extends javax.swing.JDialog {
    private FachadaAplicacion fa;
    private java.util.ArrayList<Categoria> categoriasTotal;
    private java.util.ArrayList<Categoria> categoriasTemporales;
    
    public VAnhadirJuego(java.awt.Frame parent, boolean modal, FachadaAplicacion fa) {
        super(parent, modal);
        this.fa = fa;
        initComponents();
        
        categoriasTemporales = new ArrayList<>();
        categoriasTotal = (ArrayList<Categoria>) fa.obtenerCategorias();
        ((ModeloTablaCategorias) this.tablaCategorias.getModel()).setFilas(categoriasTotal);
        if (!categoriasTotal.isEmpty())
            this.tablaCategorias.setRowSelectionInterval(0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        datosNombreJuego = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        datosEdadRecomendada = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        boxDesarrolladora = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAnhadirCategoria = new javax.swing.JButton();
        btnSacarCategoria = new javax.swing.JButton();
        btnAnhadirJuego = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaCategorias = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCategoriasJuego = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre:");

        datosNombreJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosNombreJuegoActionPerformed(evt);
            }
        });

        jLabel2.setText("Edad recomendada:");

        jLabel3.setText("Desarrolladora:");

        jLabel4.setText("Categorías disponibles");

        jLabel5.setText("Categorías del juego");

        btnAnhadirCategoria.setText("Añadir");
        btnAnhadirCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnhadirCategoriaActionPerformed(evt);
            }
        });

        btnSacarCategoria.setText("Sacar");
        btnSacarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarCategoriaActionPerformed(evt);
            }
        });

        btnAnhadirJuego.setText("Añadir juego");
        btnAnhadirJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnhadirJuegoActionPerformed(evt);
            }
        });

        tablaCategorias.setModel(new ModeloTablaCategorias());
        jScrollPane3.setViewportView(tablaCategorias);

        tablaCategoriasJuego.setModel(new ModeloTablaCategorias());
        jScrollPane1.setViewportView(tablaCategoriasJuego);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAnhadirJuego))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(datosNombreJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(datosEdadRecomendada, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxDesarrolladora, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAnhadirCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSacarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(datosNombreJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(datosEdadRecomendada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(boxDesarrolladora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnhadirCategoria)
                        .addGap(18, 18, 18)
                        .addComponent(btnSacarCategoria))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnAnhadirJuego)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datosNombreJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosNombreJuegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datosNombreJuegoActionPerformed

    private void btnAnhadirCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnhadirCategoriaActionPerformed
        int filaSeleccionada = this.tablaCategorias.getSelectedRow();
        ModeloTablaCategorias mtCatTot = (ModeloTablaCategorias) this.tablaCategorias.getModel();
        ModeloTablaCategorias mtCatJuego = (ModeloTablaCategorias) this.tablaCategoriasJuego.getModel();
        Categoria cat = mtCatTot.obtenerCategoria(filaSeleccionada);
        if (!categoriasTemporales.contains(cat))
            this.categoriasTemporales.add(cat);
        mtCatJuego.setFilas(categoriasTemporales);
        this.tablaCategoriasJuego.setRowSelectionInterval(0, 0);
    }//GEN-LAST:event_btnAnhadirCategoriaActionPerformed

    private void btnAnhadirJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnhadirJuegoActionPerformed
        if (this.datosNombreJuego.getText().isEmpty()) {
            this.fa.muestraAvisoCorrecto("Escribe el nombre del juego.");
            return;
        } else if (this.datosEdadRecomendada.getText().isEmpty()) {
            this.fa.muestraAvisoCorrecto("Indica la edad recomendada del juego.");
            return;
        } else if (this.boxDesarrolladora.getSelectedIndex() == -1) {
            this.fa.muestraAvisoCorrecto("Indica la desarrolladora del juego.");
            return;
        } else {
        String nombreJuego = this.datosNombreJuego.getText();
        Integer edadRecomendada = Integer.parseInt(this.datosEdadRecomendada.getText());
        String desarrolladora = String.valueOf(this.boxDesarrolladora.getSelectedItem());
        fa.anhadirJuego(nombreJuego, edadRecomendada, desarrolladora, this.categoriasTemporales);
        }
    }//GEN-LAST:event_btnAnhadirJuegoActionPerformed

    private void btnSacarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarCategoriaActionPerformed
       ModeloTablaCategorias mtCatJuego = (ModeloTablaCategorias) this.tablaCategoriasJuego.getModel();
       Categoria cat = mtCatJuego.obtenerCategoria(this.tablaCategoriasJuego.getSelectedRow());
       this.categoriasTemporales.remove(cat);
       mtCatJuego.setFilas(categoriasTemporales);
       if (!categoriasTemporales.isEmpty())
           this.tablaCategoriasJuego.setRowSelectionInterval(0, 0);
    }//GEN-LAST:event_btnSacarCategoriaActionPerformed

    public void inicializarBoxes(){
        //Inicializar listado de Desarrolladoras de boxDesarrolladora
        java.util.List<Desarrolladora> desarrolladoras = fa.obtenerDesarrolladoras();
        boxDesarrolladora.addItem("");
        for(Desarrolladora des: desarrolladoras){
            boxDesarrolladora.addItem(des.getNombre());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxDesarrolladora;
    private javax.swing.JButton btnAnhadirCategoria;
    private javax.swing.JButton btnAnhadirJuego;
    private javax.swing.JButton btnSacarCategoria;
    private javax.swing.JTextField datosEdadRecomendada;
    private javax.swing.JTextField datosNombreJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaCategorias;
    private javax.swing.JTable tablaCategoriasJuego;
    // End of variables declaration//GEN-END:variables
}
