/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aplicacion.Usuario;
import java.awt.Toolkit;

/**
 *
 * @author alumnogreibd
 */
public class VMisAmigos extends javax.swing.JDialog {
    private Usuario usuario;
    
    private final aplicacion.FachadaAplicacion fa;
    /**
     * Creates new form VMisAmigos
     * @param parent
     * @param modal
     * @param fa
     */
    public VMisAmigos(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, Usuario usuario) {
        
        super(parent, modal);
        //Almacenamos una referencia a la fachada de aplicación para poder tener todas las funcionalidades disponibles
        this.fa = fa;       
        this.usuario = usuario;
        initComponents();
        //Centramos en pantalla la ventana, para evitar que aparezca en la esquina superior izquierda
        this.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width/2 -this.getWidth()/2, Toolkit.getDefaultToolkit().getScreenSize().height/2 -this.getHeight()/2);
        //Hacemos la ventana visible para el usuario
        this.setVisible(true);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiquetaNombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnSelectorAmigosTotal = new javax.swing.JToggleButton();
        ScrollTablaUsuarios = new javax.swing.JScrollPane();
        tablaJugadores = new javax.swing.JTable();
        btnBloquear = new javax.swing.JButton();
        btnVerInfoAmigo = new javax.swing.JButton();
        btnVerBloqueados = new javax.swing.JButton();
        btnHacerAmigo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        etiquetaNombre.setText("Nombre:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnSelectorAmigosTotal.setText("Mis Amigos");
        btnSelectorAmigosTotal.setToolTipText("");
        btnSelectorAmigosTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSelectorAmigosTotalMouseClicked(evt);
            }
        });
        btnSelectorAmigosTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectorAmigosTotalActionPerformed(evt);
            }
        });

        tablaJugadores.setModel(new ModeloTablaJugadores());
        ScrollTablaUsuarios.setViewportView(tablaJugadores);

        btnBloquear.setText("Bloquear");

        btnVerInfoAmigo.setText("Ver info amigo");

        btnVerBloqueados.setText("Ver Bloqueados");

        btnHacerAmigo.setText("Hacer amigo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(etiquetaNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnBuscar))
                    .addComponent(ScrollTablaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBloquear)
                    .addComponent(btnVerInfoAmigo)
                    .addComponent(btnVerBloqueados)
                    .addComponent(btnHacerAmigo)
                    .addComponent(btnSelectorAmigosTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombre)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnSelectorAmigosTotal))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ScrollTablaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnBloquear)
                        .addGap(53, 53, 53)
                        .addComponent(btnVerInfoAmigo)
                        .addGap(55, 55, 55)
                        .addComponent(btnVerBloqueados)
                        .addGap(51, 51, 51)
                        .addComponent(btnHacerAmigo)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectorAmigosTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectorAmigosTotalMouseClicked
        
    }//GEN-LAST:event_btnSelectorAmigosTotalMouseClicked

    private void btnSelectorAmigosTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectorAmigosTotalActionPerformed
        if (this.btnSelectorAmigosTotal.isSelected()){
            this.btnSelectorAmigosTotal.setText("Todos Usuarios");
        }else{
            this.btnSelectorAmigosTotal.setText("Mis Amigos");
        }
    }//GEN-LAST:event_btnSelectorAmigosTotalActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String nombre = this.campoNombre.getText();
        if(this.btnSelectorAmigosTotal.isSelected()){  //TODOS LOS USUARIOS
            
        } else { //SOLO AMIGOS
            fa.obtenerAmigos(usuario, nombre);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollTablaUsuarios;
    private javax.swing.JButton btnBloquear;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnHacerAmigo;
    private javax.swing.JToggleButton btnSelectorAmigosTotal;
    private javax.swing.JButton btnVerBloqueados;
    private javax.swing.JButton btnVerInfoAmigo;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable tablaJugadores;
    // End of variables declaration//GEN-END:variables
}
