/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aplicacion.Juego;
import aplicacion.Jugador;
import aplicacion.Logro;
/**
 *
 * @author alumnogreibd
 */
public class VVerLogros extends javax.swing.JDialog {
    
    private Juego juego;
    private Jugador jugador;
    java.util.List<Logro> logros;
    
    private final aplicacion.FachadaAplicacion fa;
    /**
     * Creates new form VVerLogros
     */
    public VVerLogros(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, Juego juego, Jugador jugador) {
        super(parent, modal);
        this.juego=juego;
        this.jugador=jugador;
        this.fa=fa;
        
        
        initComponents();
        logros = fa.obtenerLogros(juego);
        ((ModeloTablaLogros)tablaLogros.getModel()).setFilas(logros);
        
        this.setVisible(true);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablaLogros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaLogros.setModel(new ModeloTablaLogros());
        jScrollPane2.setViewportView(tablaLogros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaLogros;
    // End of variables declaration//GEN-END:variables
}
